# Generated by Django 2.2.3 on 2019-08-04 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Time_and_date',
            field=models.CharField(default=datetime.datetime(2019, 8, 4, 12, 3, 2, 407876), max_length=20),
        ),
    ]
